/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP Omen
 */
public class IzmeniKlijenta extends javax.swing.JFrame {

    /**
     * Creates new form IzmeniKlijenta
     */
    public IzmeniKlijenta(){
        
        initComponents();
        try{
        popuniMeni();}
        catch(Exception ex){
            
        }
    }
    
        public void popuniPolja(){
         String [] niz=jmeni.getSelectedItem().toString().split(" ");
        int id= Integer.parseInt(niz[0]);
        try {  
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DodajKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    Connection con = null;  
    
        try {  
            
            con = (Connection) DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/hotel_niksic","root","");
            String upit="Select ime, prezime, adresa, brojTelefona, email from klijenti where klijentiID="+id;
            PreparedStatement st;
            st = con.prepareStatement(upit);
           // st.setInt(1, id);
            ResultSet rs= st.executeQuery(upit);
            while(rs.next()){
            jime.setText(rs.getString("ime"));
            jprezime.setText(rs.getString("prezime"));
            jadresa.setText(rs.getString("adresa"));
            jbrojtelefona.setText(rs.getString("brojTelefona"));
            jemail.setText(rs.getString("email"));
        }
        con.close();
        } catch (SQLException ex) {
            Logger.getLogger(ObrisiKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
        public void popuniMeni() throws SQLException{
        jmeni.removeAllItems();
     try {  
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DodajKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connection con = null;  
        con = (Connection) DriverManager.getConnection(  
                    "jdbc:mysql://localhost:3306/hotel_niksic","root","");
    
        String upit="Select klijentiID, ime, prezime from klijenti";
        Statement st=(Statement) con.createStatement();
        ResultSet rs= st.executeQuery(upit);
        
        while(rs.next()){
            jmeni.addItem(rs.getString(1)+ " "+ rs.getString(2)+" "+ rs.getString(3));
        }
        con.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmeni = new javax.swing.JComboBox();
        jime = new javax.swing.JTextField();
        jprezime = new javax.swing.JTextField();
        jadresa = new javax.swing.JTextField();
        jbrojtelefona = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jizaberi = new javax.swing.JButton();
        jizmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmeni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jime.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jime.setText("Ime");
        jime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimeActionPerformed(evt);
            }
        });

        jprezime.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jprezime.setText("Prezime");

        jadresa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jadresa.setText("Adresa");

        jbrojtelefona.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbrojtelefona.setText("Broj Telefona");

        jemail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jemail.setText("E-mail");

        jizaberi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jizaberi.setText("Izaberi klijenta");
        jizaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jizaberiActionPerformed(evt);
            }
        });

        jizmeni.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jizmeni.setText("Izmeni klijenta");
        jizmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jizmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbrojtelefona, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jprezime, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jadresa, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jime, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmeni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jizaberi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jizmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jprezime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jadresa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jbrojtelefona, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jemail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jizaberi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jizmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jizaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jizaberiActionPerformed
        
        popuniPolja();
    }//GEN-LAST:event_jizaberiActionPerformed

    private void jizmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jizmeniActionPerformed
        String upit="Update klijenti set ime=?, prezime=?, adresa=?, brojTelefona=?, email=? where klijentiID=?";
        String [] niz=jmeni.getSelectedItem().toString().split(" ");
        int id= Integer.parseInt(niz[0]);
        try {  
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DodajKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    Connection con = null;  
    
        try {  
            
            con = (Connection) DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/hotel_niksic","root","");
            PreparedStatement st;
            st = con.prepareStatement(upit);
            st.setString(1, jime.getText());
            st.setString(2, jprezime.getText());
            st.setString(3, jadresa.getText());
            st.setString(4, jbrojtelefona.getText());
            st.setString(5, jemail.getText());
            st.setInt(6, id);
            st.executeUpdate();
            con.close();
            popuniMeni();
           // st.setInt(1, id);
            
        
        } catch (SQLException ex) {
            Logger.getLogger(ObrisiKlijenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jizmeniActionPerformed

    private void jimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmeniKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmeniKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmeniKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmeniKlijenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               try {
                   new IzmeniKlijenta().setVisible(true);
               } catch (Exception ex) {
                   Logger.getLogger(IzmeniKlijenta.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jadresa;
    private javax.swing.JTextField jbrojtelefona;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jime;
    private javax.swing.JButton jizaberi;
    private javax.swing.JButton jizmeni;
    private javax.swing.JComboBox jmeni;
    private javax.swing.JTextField jprezime;
    // End of variables declaration//GEN-END:variables
}
